# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class E1s < Formula
  desc "e1s is a terminal application to simply browsing and manage AWS ECS resources, with a focus on Fargate. Inspired by k9s."
  homepage "https://github.com/keidarcy/e1s"
  version "1.0.40"

  on_macos do
    url "https://github.com/keidarcy/e1s/releases/download/v1.0.40/e1s_1.0.40_darwin_all.tar.gz"
    sha256 "a93ec0a2cf084a5a10badd776bbf593e78e45b50034bfa402ffa5d8e1bea90df"

    def install
      bin.install "e1s"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/keidarcy/e1s/releases/download/v1.0.40/e1s_1.0.40_linux_amd64.tar.gz"
        sha256 "45db445e7884c6a3e494d77d0afb6f478f285255b49239829ee207f6070813e3"

        def install
          bin.install "e1s"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/keidarcy/e1s/releases/download/v1.0.40/e1s_1.0.40_linux_arm64.tar.gz"
        sha256 "8a566bacdc7efd894c72f85ed2f80c07dad21079747d5ef96e5fe02fa34e7a47"

        def install
          bin.install "e1s"
        end
      end
    end
  end
end
