# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class E1s < Formula
  desc "e1s is a terminal application to simply browsing and manage AWS ECS resources, with a focus on Fargate. Inspired by k9s."
  homepage "https://github.com/keidarcy/e1s"
  version "1.0.27"

  on_macos do
    url "https://github.com/keidarcy/e1s/releases/download/v1.0.27/e1s_1.0.27_darwin_all.tar.gz"
    sha256 "a12fef15770b3c14192278ca8735b86e840b40f6baed56f8e19f5692d377f062"

    def install
      bin.install "e1s"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/keidarcy/e1s/releases/download/v1.0.27/e1s_1.0.27_linux_amd64.tar.gz"
      sha256 "ecf75a6b675b17a7befd475476ee3669037f5cf817b991a859117f6db9cbe042"

      def install
        bin.install "e1s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keidarcy/e1s/releases/download/v1.0.27/e1s_1.0.27_linux_arm64.tar.gz"
      sha256 "1285be3c3c19b975603ef936a5df753d00f9e42abfece33bf781ec11a04170a6"

      def install
        bin.install "e1s"
      end
    end
  end
end
